nome = input("digite seu nome:")
print(type(nome))
print("só tem espaços?", nome.isspace())
print("é um numero?", nome.isnumeric())
print("é alfabético?", nome.isalpha())
print("é alfanumérico?", nome.isalnum())
print("está em maiusculo?", nome.isupper())
print("está em minusculo?", nome.islower())
print("está capitalizada?", nome.istitle())